### ISSUE TITLE
TextEncoder is not defined errors when importing fgbFetchAll

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#257]
I'm using the dev container workflow so I'm not really sure how I could be running into this problem when nobody else is. I've tried swapping between running this as a smoke vs unit test and it doesn't make any difference.

```
Test suite failed to run

    ReferenceError: TextEncoder is not defined

      1 | import { MultiPolygon, Polygon, Sketch, SketchCollection, overlapArea, overlapFeatures, getFlatGeobufFilename, isInternalVectorDatasource } from "@seasketch/geoprocessing";
      2 | import project from "../../project";
    > 3 | import {
        | ^
      4 |   fgbFetchAll,
      5 | } from "@seasketch/geoprocessing/dataproviders";
      6 | import bbox from "@turf/bbox";

      at Object.<anonymous> (node_modules/flatgeobuf/src/ts/generic/feature.ts:9:21)
      at Object.<anonymous> (node_modules/flatgeobuf/src/ts/geojson/feature.ts:5:1)
      at Object.<anonymous> (node_modules/flatgeobuf/src/ts/geojson/featurecollection.ts:5:1)
      at Object.<anonymous> (node_modules/flatgeobuf/src/ts/geojson.ts:1:1)
      at Object.<anonymous> (node_modules/@seasketch/geoprocessing/src/dataproviders/flatgeobuf.ts:23:1)
      at Object.<anonymous> (node_modules/@seasketch/geoprocessing/src/dataproviders/index.ts:3:1)
      at Object.<anonymous> (node_modules/@seasketch/geoprocessing/dataproviders.ts:4:1)
      at Object.<anonymous> (src/functions/rocksAndIslands.ts:3:1)
      at Object.<anonymous> (src/functions/rocksAndIslands.test.ts:1:1)
```

There's a polyfill at the top of fgbFetchAll.ts that should defined TextEncoder but the import statements deep into flatgeobuf seem to run before anything related to require('') is called. I created a local version as a workaround using require statements to get the flatgeobuf exports and it seems to work.

```
// @ts-ignore
import { ReadableStream } from "web-streams-polyfill/ponyfill";
import { takeAsync } from "flatgeobuf/lib/cjs/streams/utils";
import { BBox, Feature, Geometry } from "@seasketch/geoprocessing";

//@ts-ignore
global["ReadableStream"] = ReadableStream;

// support older nodejs
if (typeof TextDecoder === "undefined" && typeof require !== "undefined") {
  (global as any).TextDecoder = require("util").TextDecoder;
}
//@ts-ignore
global["TextDecoder"] = TextDecoder;

// support older nodejs
if (typeof TextEncoder === "undefined" && typeof require !== "undefined") {
  (global as any).TextEncoder = require("util").TextEncoder;
}
//@ts-ignore
global["TextEncoder"] = TextEncoder;
export const fgbDeserialize =  require("flatgeobuf/lib/cjs/geojson").deserialize;

const { deserialize } =  require("flatgeobuf/lib/cjs/geojson");

export function fgBoundingBox(box: BBox) {
  return {
    minX: box[0],
    maxX: box[2],
    minY: box[1],
    maxY: box[3],
  };
}
```

**Comment by twelch** [comment]
Hmm this code hasn't been touched in some time, so it doesn't ring any bells.

Is this the first time you've used this fgb module? Is this a new bug with gp v6.0 you didn't get before?

Do you have the latest workspace docker image for your devcontainer? It's not versioned but you could compare changelog release date to what local docker says.

I actually use Ubuntu on windows wsl2 for my local dev. Devcontainer sparingly just because it's slower on windows.

**Comment by twelch** [comment]
This is replaced in upcoming v7 with use of Node 20 and latest flatgeobuf
