### ISSUE TITLE
Every new project has a certain little warning in test output, unclear what is causing this

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#385]
error polygon1 ValidationError: Feature is outside of boundary
at Module.clipToPolygonFeatures (file:///workspaces/test-three/node_modules/@seasketch/geoprocessing/src/toolbox/genPreprocessor.ts:155:11)
at clipToOceanEez (/workspaces/test-three/src/functions/clipToOceanEez.ts:52:10)

**Comment by avmey** [comment]
@twelch I'm not able to reproduce this so far. I created two test features like this:
```
npx tsx scripts/genRandomPolygon.ts --outDir examples/features --filename polygon1.json --bbox "[135.31244183762126,-1.1731109652985907,165.67652822599732,13.445432925389298]"
npx tsx scripts/genRandomPolygon.ts --outDir examples/features --filename polygon2.json
```

The only new output I'm seeing is this deprecation notice: `[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`

I initialized with `7.0.0-experimental-getFeatures-and-friends.8`
